// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_HQ4r0U_W0Loaal8FV-SR2TJteSpsD-o',
    appId: '1:452620507692:web:3c14953ed8e54e99750f89',
    messagingSenderId: '452620507692',
    projectId: 'chat-app-6c263',
    authDomain: 'chat-app-6c263.firebaseapp.com',
    storageBucket: 'chat-app-6c263.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4OZXWGpmLV0iUe5NmA4M8hy6ubiAleAY',
    appId: '1:452620507692:android:abd3ffbf219adc65750f89',
    messagingSenderId: '452620507692',
    projectId: 'chat-app-6c263',
    storageBucket: 'chat-app-6c263.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNRAkOn2g1edEtu3eRe7nZuJnMV3BMR18',
    appId: '1:452620507692:ios:61cf69e121e2502c750f89',
    messagingSenderId: '452620507692',
    projectId: 'chat-app-6c263',
    storageBucket: 'chat-app-6c263.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNRAkOn2g1edEtu3eRe7nZuJnMV3BMR18',
    appId: '1:452620507692:ios:61cf69e121e2502c750f89',
    messagingSenderId: '452620507692',
    projectId: 'chat-app-6c263',
    storageBucket: 'chat-app-6c263.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_HQ4r0U_W0Loaal8FV-SR2TJteSpsD-o',
    appId: '1:452620507692:web:e797f1126dd44722750f89',
    messagingSenderId: '452620507692',
    projectId: 'chat-app-6c263',
    authDomain: 'chat-app-6c263.firebaseapp.com',
    storageBucket: 'chat-app-6c263.appspot.com',
  );
}
